=begin
#DocuSign Monitor API - v2

#An API for an integrator to access the features of DocuSign Monitor

OpenAPI spec version: v2.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'docusign_monitor/client/api_client'
require 'docusign_monitor/client/api_error'
require 'docusign_monitor/version'
require 'docusign_monitor/configuration'

# Client Files
require 'docusign_monitor/client/auth/oauth'

# Models
require 'docusign_monitor/models/cursored_result'

# APIs
require 'docusign_monitor/api/data_set_api'

module DocuSign_Monitor
  class << self
    # Customize default settings for the SDK using block.
    #   DocuSign_Monitor.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end