=begin
#Monitor API

#An API for an integrator to access the features of Docusign Monitor

OpenAPI spec version: v3.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

# Common files
require 'docusign_monitor/client/api_client'
require 'docusign_monitor/client/api_error'
require 'docusign_monitor/version'
require 'docusign_monitor/configuration'

# Client Files
require 'docusign_monitor/client/auth/oauth'

# Models
require 'docusign_monitor/models/browser'
require 'docusign_monitor/models/device'
require 'docusign_monitor/models/ip_address_location'
require 'docusign_monitor/models/os'
require 'docusign_monitor/models/stream_response'
require 'docusign_monitor/models/streaming_event_row'
require 'docusign_monitor/models/user_agent_client_info'
require 'docusign_monitor/models/version'

# APIs
require 'docusign_monitor/api/docu_monitor_api'

module DocuSign_Monitor
  class << self
    # Customize default settings for the SDK using block.
    #   DocuSign_Monitor.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end