=begin
#DocuSign Monitor API - v2

#An API for an integrator to access the features of DocuSign Monitor

OpenAPI spec version: v2.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

module DocuSign_Monitor
  VERSION = '1.0.0.beta1'
end
