=begin
#Monitor API

#An API for an integrator to access the features of Docusign Monitor

OpenAPI spec version: v3.0
Contact: devcenter@docusign.com
Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module DocuSign_Monitor
  class StreamingEventRow
    attr_accessor :timestamp

    attr_accessor :event_id

    attr_accessor :site

    attr_accessor :account_id

    attr_accessor :organization_id

    attr_accessor :user_id

    attr_accessor :integrator_key

    attr_accessor :user_agent

    attr_accessor :user_agent_client_info

    attr_accessor :ip_address

    attr_accessor :ip_address_location

    attr_accessor :object

    attr_accessor :action

    attr_accessor :property

    attr_accessor :field

    attr_accessor :result

    attr_accessor :source

    attr_accessor :is_user_member_of_domain

    attr_accessor :referenced_user_is_member_of_domain

    attr_accessor :referenced_user_id

    attr_accessor :proxy_status

    attr_accessor :proxy_type

    attr_accessor :proxy_level

    attr_accessor :latitude

    attr_accessor :longitude

    attr_accessor :city

    attr_accessor :state

    attr_accessor :country

    attr_accessor :device

    attr_accessor :browser

    attr_accessor :os

    attr_accessor :affected_user_id

    attr_accessor :affected_user_is_member_of_domain

    attr_accessor :data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'timestamp' => :'timestamp',
        :'event_id' => :'eventId',
        :'site' => :'site',
        :'account_id' => :'accountId',
        :'organization_id' => :'organizationId',
        :'user_id' => :'userId',
        :'integrator_key' => :'integratorKey',
        :'user_agent' => :'userAgent',
        :'user_agent_client_info' => :'userAgentClientInfo',
        :'ip_address' => :'ipAddress',
        :'ip_address_location' => :'ipAddressLocation',
        :'object' => :'object',
        :'action' => :'action',
        :'property' => :'property',
        :'field' => :'field',
        :'result' => :'result',
        :'source' => :'source',
        :'is_user_member_of_domain' => :'isUserMemberOfDomain',
        :'referenced_user_is_member_of_domain' => :'referencedUserIsMemberOfDomain',
        :'referenced_user_id' => :'referencedUserId',
        :'proxy_status' => :'proxyStatus',
        :'proxy_type' => :'proxyType',
        :'proxy_level' => :'proxyLevel',
        :'latitude' => :'latitude',
        :'longitude' => :'longitude',
        :'city' => :'city',
        :'state' => :'state',
        :'country' => :'country',
        :'device' => :'device',
        :'browser' => :'browser',
        :'os' => :'os',
        :'affected_user_id' => :'affectedUserId',
        :'affected_user_is_member_of_domain' => :'affectedUserIsMemberOfDomain',
        :'data' => :'data'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'timestamp' => :'DateTime',
        :'event_id' => :'String',
        :'site' => :'String',
        :'account_id' => :'String',
        :'organization_id' => :'String',
        :'user_id' => :'String',
        :'integrator_key' => :'String',
        :'user_agent' => :'String',
        :'user_agent_client_info' => :'UserAgentClientInfo',
        :'ip_address' => :'String',
        :'ip_address_location' => :'IpAddressLocation',
        :'object' => :'String',
        :'action' => :'String',
        :'property' => :'String',
        :'field' => :'String',
        :'result' => :'String',
        :'source' => :'String',
        :'is_user_member_of_domain' => :'BOOLEAN',
        :'referenced_user_is_member_of_domain' => :'BOOLEAN',
        :'referenced_user_id' => :'String',
        :'proxy_status' => :'String',
        :'proxy_type' => :'String',
        :'proxy_level' => :'String',
        :'latitude' => :'Float',
        :'longitude' => :'Float',
        :'city' => :'String',
        :'state' => :'String',
        :'country' => :'String',
        :'device' => :'String',
        :'browser' => :'String',
        :'os' => :'String',
        :'affected_user_id' => :'String',
        :'affected_user_is_member_of_domain' => :'BOOLEAN',
        :'data' => :'Hash<String, Object>'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'timestamp')
        self.timestamp = attributes[:'timestamp']
      end

      if attributes.has_key?(:'eventId')
        self.event_id = attributes[:'eventId']
      end

      if attributes.has_key?(:'site')
        self.site = attributes[:'site']
      end

      if attributes.has_key?(:'accountId')
        self.account_id = attributes[:'accountId']
      end

      if attributes.has_key?(:'organizationId')
        self.organization_id = attributes[:'organizationId']
      end

      if attributes.has_key?(:'userId')
        self.user_id = attributes[:'userId']
      end

      if attributes.has_key?(:'integratorKey')
        self.integrator_key = attributes[:'integratorKey']
      end

      if attributes.has_key?(:'userAgent')
        self.user_agent = attributes[:'userAgent']
      end

      if attributes.has_key?(:'userAgentClientInfo')
        self.user_agent_client_info = attributes[:'userAgentClientInfo']
      end

      if attributes.has_key?(:'ipAddress')
        self.ip_address = attributes[:'ipAddress']
      end

      if attributes.has_key?(:'ipAddressLocation')
        self.ip_address_location = attributes[:'ipAddressLocation']
      end

      if attributes.has_key?(:'object')
        self.object = attributes[:'object']
      end

      if attributes.has_key?(:'action')
        self.action = attributes[:'action']
      end

      if attributes.has_key?(:'property')
        self.property = attributes[:'property']
      end

      if attributes.has_key?(:'field')
        self.field = attributes[:'field']
      end

      if attributes.has_key?(:'result')
        self.result = attributes[:'result']
      end

      if attributes.has_key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.has_key?(:'isUserMemberOfDomain')
        self.is_user_member_of_domain = attributes[:'isUserMemberOfDomain']
      end

      if attributes.has_key?(:'referencedUserIsMemberOfDomain')
        self.referenced_user_is_member_of_domain = attributes[:'referencedUserIsMemberOfDomain']
      end

      if attributes.has_key?(:'referencedUserId')
        self.referenced_user_id = attributes[:'referencedUserId']
      end

      if attributes.has_key?(:'proxyStatus')
        self.proxy_status = attributes[:'proxyStatus']
      end

      if attributes.has_key?(:'proxyType')
        self.proxy_type = attributes[:'proxyType']
      end

      if attributes.has_key?(:'proxyLevel')
        self.proxy_level = attributes[:'proxyLevel']
      end

      if attributes.has_key?(:'latitude')
        self.latitude = attributes[:'latitude']
      end

      if attributes.has_key?(:'longitude')
        self.longitude = attributes[:'longitude']
      end

      if attributes.has_key?(:'city')
        self.city = attributes[:'city']
      end

      if attributes.has_key?(:'state')
        self.state = attributes[:'state']
      end

      if attributes.has_key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.has_key?(:'device')
        self.device = attributes[:'device']
      end

      if attributes.has_key?(:'browser')
        self.browser = attributes[:'browser']
      end

      if attributes.has_key?(:'os')
        self.os = attributes[:'os']
      end

      if attributes.has_key?(:'affectedUserId')
        self.affected_user_id = attributes[:'affectedUserId']
      end

      if attributes.has_key?(:'affectedUserIsMemberOfDomain')
        self.affected_user_is_member_of_domain = attributes[:'affectedUserIsMemberOfDomain']
      end

      if attributes.has_key?(:'data')
        if (value = attributes[:'data']).is_a?(Hash)
          self.data = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          timestamp == o.timestamp &&
          event_id == o.event_id &&
          site == o.site &&
          account_id == o.account_id &&
          organization_id == o.organization_id &&
          user_id == o.user_id &&
          integrator_key == o.integrator_key &&
          user_agent == o.user_agent &&
          user_agent_client_info == o.user_agent_client_info &&
          ip_address == o.ip_address &&
          ip_address_location == o.ip_address_location &&
          object == o.object &&
          action == o.action &&
          property == o.property &&
          field == o.field &&
          result == o.result &&
          source == o.source &&
          is_user_member_of_domain == o.is_user_member_of_domain &&
          referenced_user_is_member_of_domain == o.referenced_user_is_member_of_domain &&
          referenced_user_id == o.referenced_user_id &&
          proxy_status == o.proxy_status &&
          proxy_type == o.proxy_type &&
          proxy_level == o.proxy_level &&
          latitude == o.latitude &&
          longitude == o.longitude &&
          city == o.city &&
          state == o.state &&
          country == o.country &&
          device == o.device &&
          browser == o.browser &&
          os == o.os &&
          affected_user_id == o.affected_user_id &&
          affected_user_is_member_of_domain == o.affected_user_is_member_of_domain &&
          data == o.data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [timestamp, event_id, site, account_id, organization_id, user_id, integrator_key, user_agent, user_agent_client_info, ip_address, ip_address_location, object, action, property, field, result, source, is_user_member_of_domain, referenced_user_is_member_of_domain, referenced_user_id, proxy_status, proxy_type, proxy_level, latitude, longitude, city, state, country, device, browser, os, affected_user_id, affected_user_is_member_of_domain, data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = DocuSign_Monitor.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
